[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ['@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/', '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts']


[invariant]
runs = 128
depth = 128
fail_on_revert = true

#depth = the number of calls in each run
# fail_on_revert = false is good for quick tests,
# fail_on_revert = true perform deeper tests and will fail if a revert is encountered in each run
# fail_on_revert = true will produce different error (or function call) whne the actual contracts has multiple functions



# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config   


